"""Allow property_id to be nullable in Tenant

Revision ID: 62372b905f6f
Revises: a19e14c51c27
Create Date: 2025-04-17 05:51:42.434265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62372b905f6f'
down_revision = 'a19e14c51c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
